### ISSUE TITLE
Permission denied running version command when targeting Android Q

### ISSUE THREAD

**Issue by darrinps** [bravobit/FFmpeg-Android#126]
Not sure if it's because I am running Android Q beta, or I'm doing something wrong but I am getting the following:

2019-07-26 12:29:01.320 24329-24408/com.android.testffmpeg E/FFmpeg: Exception while trying to run: [/data/user/0/com.android.testffmpeg/files/ffmpeg, -version]
    java.io.IOException: Cannot run program "/data/user/0/com.android.testffmpeg/files/ffmpeg": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15)

All I am doing is calling this function:

`                            
                               private fun versionFFmpeg() {
                                 FFmpeg.getInstance(TestFFmpegApplication.instance.applicationContext)
            .execute(arrayOf("-version"), object : ExecuteBinaryResponseHandler() {
                override fun onSuccess(message: String?) {
                    Timber.d(message)
                }

                override fun onProgress(message: String?) {
                    Timber.d(message)
                }
            })

    }
`

The only setup I have in the code is this:

implementation 'nl.bravobit:android-ffmpeg:1.1.7'

Can anyone see what it is I am missing, or perhaps there is an issue running on Android Q?

**Comment by darrinps** [comment]
Looks like it's Q. If I build and run your sample app verbatim, it works, but when I change the compile and target SDK to be 29....crash. Same as I see in my app. So I think this looks to be a fairly high bug given Q will be released shortly.

**Comment by alexcohn** [comment]
<s>Tried this on Q emulator, `system-images\android-29\google_apis\x86`, and it simply worked. </s>

**Comment by alexcohn** [comment]
I have updated the **Q** emulator (now it is ` [google/sdk_gphone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:userdebug/dev-keys]`), and the it does not permit to run **ffmpeg** from the **files** directories anymore. Or maybe the trigger is that I set targetSdk=29.

Actually, this is a [documented](https://developer.android.com/preview/behavior-changes-all#execute-permission) change.

The fix is to move ffmpeg from **assets** to **jniLibs**.

**Comment by desaibijal** [comment]
Someone has solution to run ffmpeg commands in android Q its urgent??

**Comment by kartik1225** [comment]
Any updates on this?

**Comment by kazemihabib** [comment]
Hi,
I didn't try it myself but probably you can fix it with adding

   `android:requestLegacyExternalStorage="true"`

to `application` in AndroidManifest.xml

**Comment by kartik1225** [comment]
No, it still does not work

**Comment by WassimErriha** [comment]
Try this [library][1] 
I just tested it on a physical device running Android Q (android 10)


  [1]: https://github.com/tanersener/mobile-ffmpeg

**Comment by PO15ON** [comment]
@WassimErriha Thanks, it worked.

**Comment by Aditya94A** [comment]
Any updates on this?

Or is this the end of this library?

**Comment by Le-Dinh-Nam** [comment]
I found solution on this issue.
https://issuetracker.google.com/issues/128554619

exec() no longer works on files within the application home directory, it continues to be supported for files within the read-only /data/app directory. In particular, it should be possible to package the binaries into your application's native libs directory and enable android:extractNativeLibs=true, and then call exec() on the /data/app artifacts. A similar approach is done with the wrap.sh functionality, documented at https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh . 

It works well on my project(tested on Pixel 3a XL android Q)

**Comment by AmioLee** [comment]
> I have updated the **Q** emulator (now it is ` [google/sdk_gphone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:userdebug/dev-keys]`), and the it does not permit to run **ffmpeg** from the **files** directories anymore. Or maybe the trigger is that I set targetSdk=29.
> 
> Actually, this is a [documented](https://developer.android.com/preview/behavior-changes-all#execute-permission) change.
> 
> The fix is to move ffmpeg from **assets** to **jniLibs**.

I have create jniLibs folder then move the lib from assets,but still not work, 
Is there something i miss?

**Comment by alexcohn** [comment]
> I have create jniLibs folder then move the lib from assets,but still not work,
> Is there something i miss?

It's much more than simply renaming some folders, see https://github.com/bravobit/FFmpeg-Android/pull/130

**Comment by vincent-paing** [comment]
Why hasn't this been merged yet, even Android 11 is about be released, has this project been abandoned?

**Comment by pratikbutani** [comment]
Just change targetSdkVersion 29 to **28** in `build.gradle`

It worked for me.

**Comment by kibotu** [comment]
@pratikbutani not a solution that works on higher android versions

**Comment by pratikbutani** [comment]
@kibotu 
It's working on higher version too. I have checked on Android 10.

**Comment by SnehaDZ** [comment]
not working for me

**Comment by aliraza96** [comment]
NOT WORKING FOR ME TOO. Have anyone found an answer to this problem?

**Comment by alexcohn** [comment]
@SnehaDZ @aliraza96 if you can set targetSdkVersion less than 29, your app will continue to work even on Android 11 (a.k.a. Android R). Note that this does not prevent you from using the new Android Q APIs in your code.

But if you want to switch to 29, you can try [my fork](https://github.com/alexcohn/FFmpeg-Android/tree/pull_request_Q). In the long run, I would recommend to switch to [another library](https://github.com/tanersener/mobile-ffmpeg), even though this means that your code must be changed: with every upgrade, Android becomes less open to running executables in the context of an app.

**Comment by sureapps** [comment]
But if you want to switch to 29, you can try my fork. In the long run, I would recommend to switch to another library, even though this means that your code must be changed: with every upgrade, Android becomes less open to running executables in the context of an app.
Android Q in work perfectly but 
Pull_request_29 is not running 4.4, 5.0 or I think 32 bit not support because of this resources not available in File folder = new File(context.getApplicationInfo().nativeLibraryDir); this directory so how to solve this problem.

**Comment by Ahmed-Basalib10** [comment]
any update ?

**Comment by kdsrsl** [comment]
still unrepaired

**Comment by iamkdblue** [comment]
any update?

**Comment by vincent-paing** [comment]
We're using this library instead now, which is still maintained actively

https://github.com/tanersener/mobile-ffmpeg

**Comment by 1nikolas** [comment]
You can take a look on [my approach](https://github.com/WritingMinds/ffmpeg-android-java/pull/361) on the original repo. I basically moved ffmpeg to the libs folder and renamed it to libffmpeg.so (should start with lib and end with .so in order for this to work). Then I added `android:extractNativeLibs = "true"` to the manifest so the binary is moved into `data/app/{package_name}/lib/{arch}/`, where it can me executed on Android 10.

There is a problem with this though. You have to put the binaries 4 times in the apk (if you want an apk that supports all architectures). The only way to have the binaries 2 times is to [build the apk for arm and x86 only](https://github.com/WritingMinds/ffmpeg-android-java/pull/361#issuecomment-656107645) (so it can use the x86 binary on x64 and arm binary for arm64). But then playstore [wont let you upload your app](https://9to5google.com/wp-content/uploads/sites/4/2019/01/android-app-64-bit-requirement.png) because it doesn't have native x64 support.

**Comment by AamirNaseer1** [comment]
> I have updated the **Q** emulator (now it is ` [google/sdk_gphone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:userdebug/dev-keys]`), and the it does not permit to run **ffmpeg** from the **files** directories anymore. Or maybe the trigger is that I set targetSdk=29.
> 
> Actually, this is a [documented](https://developer.android.com/preview/behavior-changes-all#execute-permission) change.
> 
> The fix is to move ffmpeg from **assets** to **jniLibs**.

how can I move from assets to JNI libs?

**Comment by iamkdblue** [comment]
use this 
`    implementation 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS'
`

**Comment by plazar99** [comment]
> use this
> ` implementation 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS'`

I tried this, ffmpeg -version hits onFailure.
do I need to do load library with this version. The 0.3.2 from writingminds required it.

**Comment by alexcohn** [comment]
@plazar99 normally, the library loads its native part by itself. But your mileage may vary.

**Comment by plazar99** [comment]
I just rebuild it for sdktarget 28, no difference. I'm afraid I'm missing something fundamental here.

**Comment by plazar99** [comment]
I figured out my mistake. I followed the example provided, 
1. implementation 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS'   <=== do not use this
===> use this     implementation 'nl.bravobit:android-ffmpeg:1.1.7'

2.use this =>                ffmpeg.execute(ffcommand, new FFcommandExecuteResponseHandler() {
dont use the one in the example provided.

This fixed everything.

**Comment by nivas412** [comment]
> You can take a look on [my approach](https://github.com/WritingMinds/ffmpeg-android-java/pull/361) on the original repo. I basically moved ffmpeg to the libs folder and renamed it to libffmpeg.so (should start with lib and end with .so in order for this to work). Then I added `android:extractNativeLibs = "true"` to the manifest so the binary is moved into `data/app/{package_name}/lib/{arch}/`, where it can me executed on Android 10.
> 
> There is a problem with this though. You have to put the binaries 4 times in the apk (if you want an apk that supports all architectures). The only way to have the binaries 2 times is to [build the apk for arm and x86 only](https://github.com/WritingMinds/ffmpeg-android-java/pull/361#issuecomment-656107645) (so it can use the x86 binary on x64 and arm binary for arm64). But then playstore [wont let you upload your app](https://9to5google.com/wp-content/uploads/sites/4/2019/01/android-app-64-bit-requirement.png) because it doesn't have native x64 support.

How you moved ??

**Comment by aliraza96** [comment]
I didn't. I just used EpMedia Library. That is totally better than  this.
It uses FFMPEG at it's backend. But it automatically handles all these cases

**Comment by kadnan0900** [comment]
i didn't see any clear fixed please guide me to solve this issue.

**Comment by alexcohn** [comment]
> i didn't see any clear fixed please guide me to solve this issue.

See https://github.com/bravobit/FFmpeg-Android/issues/126#issuecomment-627155158

**Comment by plazar99** [comment]
I gave up on this version of ffmpeg, I was able to get it working, but noticed that when running large number of ffmpeg (120) the number of failures were too much. I went back to the older version from writing minds, this gave me zero failures.
I spent too much time on it and my project was due. The build runs with android11 well,  I set my target sdk to 28.

**Comment by kadnan0900** [comment]
@plazar99 but when you upload app on playstore you have to upgrade your tarketsdkversion to 29 thats the major issue.

**Comment by mans17312** [comment]
Facing this issue, have any one fixed it so far ?

**Comment by mans17312** [comment]
Here is the issue, only for android 10+ devices
Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:699)

**Comment by SyedSaadUrRehman-MAD** [comment]
bravobits-ffmpeg works for on android 12 with target set to 28, no more permission denied froom ffmpeg after i added "-y" in the start of my every ffmpeg-command
