### ISSUE TITLE
java.io.IOException: ffmpeg": error=13, Permission denied

### ISSUE THREAD

**Issue by vipin00147** [bravobit/FFmpeg-Android#181]
Hi there, I am getting this issue........

at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
                                                                                                    	at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15)
                                                                                                    	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43)
                                                                                                    	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:378)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    Caused by: java.io.IOException: error=13, Permission denied
                                                                                                    	at java.lang.UNIXProcess.forkAndExec(Native Method)
                                                                                                    	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
                                                                                                    	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
                                                                                                    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

**Comment by midhundevcodes** [comment]
Hi @vipin00147 did you fix the issue ??

**Comment by vipin00147** [comment]
Nopp, actually I don't know the root cause of the problem

**Comment by Dsyboot** [comment]
This is one of the problems I have currently presented, and it is all the fault of the android 13+ version, since it prevents the execution of binaries, showing the Permission Denied error

Edit:

I found this post, In one part someone said the reason why this doesn't work, and it's because of the targetSdkVersion, It must be less than or equal to 28, because the execution of binaries is still allowed on them.

https://stackoverflow.com/questions/67974978/android-execute-binary-from-application
